## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 21](#1)
* [Ćwiczenie 22](#2)
* [Ćwiczenie 23](#3)
* [Ćwiczenie 24](#4)
* [Ćwiczenie 25](#5)
* [Ćwiczenie 26](#6)
* [Ćwiczenie 27](#7)
* [Ćwiczenie 28](#8)
* [Ćwiczenie 29](#9)
* [Ćwiczenie 30](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.24.2'

### <a name='1'></a> Ćwiczenie 21
Wygeneruj poniższą tablicę numpy. Zapisz tablicę do pliku bianarnego o nazwie _'array.npy'_ i następnie wczytaj z powrotem ten plik do innej zmiennej.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


__Wskazówka:__ Użyj funkcji _np.save()_ oraz _np.load()_.

In [5]:
tabA = np.arange(12)
tabA = tabA.reshape(3, 4)

np.save('plik_tabA', tabA)

loaded_tabA = np.load('plik_tabA.npy')

loaded_tabA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### <a name='2'></a> Ćwiczenie 22
Wygeneruj ponizszą tablicę numpy:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


Zapisz tablicę do pliku tekstowego o nazwie _'array.txt'_ z dokładnością do drugiego miejsca po przecinku i następnie wczytaj z powrotem ten plik do innej zmiennej.

__Wskazówka:__ Użyj funkcji _np.savetxt()_ oraz _np.loadtxt()_.


In [9]:
tabB = np.arange(12)
tabB = tabA.reshape(3, 4)

np.savetxt('tabB.txt', tabB, fmt='%d', delimiter=',')

loaded_tabB =np.loadtxt('tabB.txt', delimiter=',')

loaded_tabB

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### <a name='3'></a> Ćwiczenie 23
Wygeneruj i przekształć poniższą tablicę numpy na listę.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



__Wskazówka:__ Użyj metody _np.array.tolist()_.

In [11]:
tabC = np.arange(12)
tabC = tabC.reshape(3, 4)

list_tabC = tabC.tolist()
list_tabC

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### <a name='4'></a> Ćwiczenie 24
Podana jest poniższa tablica numpy:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Używając operatora wycinania przekształć tablicę w poniższe:

* zamiana wierszy (pierwszy z ostatnim)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```







In [13]:
tabD = np.arange(12)
tabD = tabD.reshape(3, 4)

tabD_revered_rows = tabD.copy()
tabD_revered_rows[[0, -1], :] = tabD_revered_rows[[-1, 0], :]

tabD_revered_rows

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

* zamiana kolumn (odwrócona kolejność)


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```


In [14]:
tabD_revered_columns = tabD.copy()
tabD_revered_columns[:, [0, 3]] = tabD_revered_columns[:, [3, 0]]
tabD_revered_columns

array([[ 3,  1,  2,  0],
       [ 7,  5,  6,  4],
       [11,  9, 10,  8]])

* zamiana wierszy i kolumn (odwrócone kolejności)


```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```       

In [20]:
tabD_revered_all = tabD.copy()

tabD_revered_all = tabD_revered_all[::-1, ::-1]

tabD_revered_all

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### <a name='5'></a> Ćwiczenie 25
Podaną poniżej tablicę numpy:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Przekształć na tablicę:


```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```
__Wskazówka:__ Użyj funkcji _np.pad()_.





In [23]:
tabE = np.ones((4, 4))
tabE = np.pad(tabE, ((1, 1), (1, 1),), mode='constant', constant_values=(0,0))
tabE


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Ćwiczenie 26
Podaną poniżej tablicę numpy:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
Przekształć na tablicę:


```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```
__Wskazówka:__ Użyj operatora wycinania oraz przypisz odpowiednie wartości.





In [33]:
tabF = np.zeros((6, 6), dtype=int)
tabF[::2, ::2] = 10
tabF[1::2, ::2] = 5
tabF

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

### <a name='7'></a> Ćwiczenie 27
Połącz podane poniżej tablice $A$ oraz $B$ w jedną.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```




__Oczekiwany rezultat:__


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```
__Wskazówka:__ Użyj funkcji _np.append()_.


In [34]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

tabG = np.append(A, B, axis=0)
tabG

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Ćwiczenie 28
Z podanych poniżej tablic $A$ i $B$ wydobądź elementy wspólne (przecięcie) tablic.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```



__Wskazówka:__ Użyj funkcji _np.intersect1d()_.

In [35]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])

tabH = np.intersect1d(A, B)
tabH

array([0, 2, 3])

### <a name='9'></a> Ćwiczenie 29
Podana jest poniższa tablica numpy $A$.
Znajdź unikalne wartości tej tablicy.


```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```


__Wskazówka:__ Użyj funkcji _np.unique()_.

In [36]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

tabI = np.unique(A)
tabI

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Ćwiczenie 30
Podana jest poniższa tablica:


```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```



Zwróć indeksy na których stoją maksymalne wartości dla danego wiersza.

__Wskazówka:__ Użyj funkcji _np.argmax()_.

In [38]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
tabJ = np.argmax(A, axis=1)
tabJ

array([0, 2, 1], dtype=int64)