## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 31](#1)
* [Ćwiczenie 32](#2)
* [Ćwiczenie 33](#3)
* [Ćwiczenie 34](#4)
* [Ćwiczenie 35](#5)
* [Ćwiczenie 36](#6)
* [Ćwiczenie 37](#7)
* [Ćwiczenie 38](#8)
* [Ćwiczenie 39](#9)
* [Ćwiczenie 40](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.24.2'

### <a name='1'></a> Ćwiczenie 31
Wykonaj dwa sortowania podanej poniżej tablicy $A$:
* wierszowo (rosnąco)
* kolumnowo (rosnąco)


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.sort()_.

In [10]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

tabAsorted_wier = np.sort(A, axis=1)
tabAsorted_kol = np.sort(A, axis=0)

print(tabAsorted_wier)
print(f"\n{tabAsorted_kol}")

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]

[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


### <a name='2'></a> Ćwiczenie 32
Wytnij wszystkie elementy tablicy $A$ o wartości wyższej niż 8.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



In [11]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

tabB = A[A > 8]
tabB

array([ 9.99,  9.99, 14.99])

### <a name='3'></a> Ćwiczenie 33
Podana jest poniższa tablica $A$. Zastąp elementy powyżej wartości 10 wartością stałą 10 (obcięcie wartości do 10).


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.where()_.

In [12]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

tabC = np.where(A>10, 10, A)

tabC

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### <a name='4'></a> Ćwiczenie 34
Poniższą dwuwymiarową tablicę $A$ przedstaw w postaci 'wypłaszczonej' jednowymiarowej tablicy.  

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Oczekiwany wynik:__


```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Wskazówka:__ Użyj funkcji _np.ravel()_.




In [13]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

tabD = np.ravel(A)

tabD

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Ćwiczenie 35
Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 0.0.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Oczekiwany wynik:__


```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```





__Wskazówka:__ Użyj funkcji _np.zeros_like()_.

In [15]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

tabE = np.zeros_like(A)

tabE

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### <a name='6'></a> Ćwiczenie 36

Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 9.99.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

__Oczekiwany wynik:__


```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```



__Wskazówka:__ Użyj funkcji _np.full_like()_.

In [16]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

tabF = np.full_like(A, fill_value=9.99)

tabF

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### <a name='7'></a> Ćwiczenie 37
Zbuduj tablicę dwuwymiarową (macierz kwadratową dolną trójkątną) podnaną poniżej:


```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```
__Wskazówka:__ Użyj funkcji _np.tri()_.


In [17]:
tabG = np.tri(5, k=0)

tabG

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### <a name='8'></a> Ćwiczenie 38
Stwórz dowolną tablicę 3-wymiarową o kształcie $(2, 3, 4)$.

In [18]:
tabH = np.random.rand(2, 3, 4)

#alternetywy dla stworzenia takiej tablicy
# tabH1 = np.zeros(2, 3, 4)
# tabH2 = np.ones(2, 3, 4)

tabH

array([[[0.44817621, 0.38625357, 0.33126448, 0.69293632],
        [0.73668646, 0.86825721, 0.34130244, 0.76505484],
        [0.31969859, 0.6179154 , 0.52092283, 0.50866703]],

       [[0.27304572, 0.41957588, 0.01756172, 0.94792254],
        [0.18836294, 0.72874132, 0.11970535, 0.13217066],
        [0.63571007, 0.75814002, 0.48500836, 0.64612609]]])

### <a name='9'></a> Ćwiczenie 39

Wygeneruj dwuwymiarową tablicę o kształcie _(200, 300)_ wypełnioną wartościami losowymi od 0 do 255 włacznie i typie danych _np.uint8_ i przypisz do zmiennej _image_.

In [26]:
image = np.random.randint(0, 256, size=(200, 300), dtype=np.uint8)

Nastepnie uruchom poniższy blok kodu. W rezultacie uzyskasz podgląd na losowo wygenerowany czarno-biały obraz.

In [29]:
# from google.colab.patches import cv2_imshow

# cv2_imshow(image)

from PIL import Image

# konwersja tablicy NumPy na obiekt PIL Image
img = Image.fromarray(image)

# zmiana trybu obrazu na "L"
img = img.convert("L")

img.show()
img.save("obraz.png")

### <a name='10'></a> Ćwiczenie 40
Tablicę _image_ z poprzedniego zadania posortuj wzdłuż wiersza rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
image.sort(axis=1)

Tablicę _image_ z poprzedniego zadania posortuj wzdłuż kolumny rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
image.sort(axis=0)